site: 
  title: Galaxy Antora Demo playbook
  url: https://arcanneero.github.io/galaxie-antora-playbook/
  start_page: galaxie-antora-demo::index.adoc 
content: 
  sources: 
  - url: https://github.com/arcanneero/galaxie-antora-demo.git 
    branches: master
  # - url: https://GITHUB_TOKEN:@github.com:arcanneero/galaxie-antora-slides.git 
  #   branches: master
  #   start_path: docs  
asciidoc: 
  attributes: 
    linkattrs: ''
    toc: ~
ui: 
  bundle:
    url: https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/master/raw/build/ui-bundle.zip?job=bundle-stable 
    snapshot: true
git:
  credentials:
    path: ../.git-credentials-galaxy-antora

